#!/usr/bin/env python3
"""
Run test vectors for signature aggregation of BIP 340 signatures
per the DahLIAS interactive signing protocol.

Usage:
    python run_test_vectors.py

Expects CSV files generated by gen_test_vectors.py in vectors/ directory.
"""

import csv
import os
import sys
from pathlib import Path
from typing import List, Tuple

from secp256k1lab.secp256k1 import G, GE, Scalar
from secp256k1lab.util import bytes_from_int, int_from_bytes

from reference import NonceAgg, Sign, SigAgg, Verify, PartialSigVerify, n


VECTORS_DIR = Path(__file__).resolve().parent / "vectors"
SIGN_VECTORS = VECTORS_DIR / "test_vectors_sign.csv"
VERIFY_VECTORS = VECTORS_DIR / "test_vectors_verify.csv"
PARTIAL_SIG_VERIFY_VECTORS = VECTORS_DIR / "test_vectors_partial_sig_verify.csv"


def parse_hex_list(hex_str: str) -> List[bytes]:
    if not hex_str:
        return []
    return [bytes.fromhex(h) for h in hex_str.split(";")]


def parse_pubnonce(b: bytes) -> Tuple[GE, GE]:
    if len(b) != 66:
        raise ValueError("pubnonce must be 66 bytes")
    return GE.from_bytes_compressed(b[:33]), GE.from_bytes_compressed(b[33:])


def parse_secnonce(b: bytes) -> Tuple[Scalar, Scalar]:
    if len(b) != 64:
        raise ValueError("secnonce must be 64 bytes")
    return Scalar(int_from_bytes(b[:32])), Scalar(int_from_bytes(b[32:]))


def parse_sig(b: bytes) -> Tuple[GE, int]:
    """Parse R (32-byte x-only) || s (32-byte big-endian).

    Lifts R to even y; raises on length mismatch or off-curve x. The s value
    is returned without range check so Verify itself exercises the s < n rule.
    """
    if len(b) != 64:
        raise ValueError("signature must be 64 bytes")
    R = GE.from_bytes_xonly(b[:32])
    s = int_from_bytes(b[32:])
    return R, s


def run_sign_tests() -> List[str]:
    failures = []

    with open(SIGN_VECTORS, newline="", encoding="utf-8") as f:
        reader = csv.reader(f)
        next(reader)

        for row in reader:
            (index, sks_str, msgs_str, secnonces_str,
             expected_aggnonce_str, expected_psigs_str,
             expected_sig_str, comment) = row

            try:
                sks = [Scalar(int_from_bytes(b)) for b in parse_hex_list(sks_str)]
                msgs = parse_hex_list(msgs_str)
                secnonces = [parse_secnonce(b) for b in parse_hex_list(secnonces_str)]
                expected_aggnonce = bytes.fromhex(expected_aggnonce_str)
                expected_psigs = parse_hex_list(expected_psigs_str)
                expected_sig = bytes.fromhex(expected_sig_str)

                pks = [sk * G for sk in sks]
                pubnonces = [(r1 * G, r2 * G) for (r1, r2) in secnonces]

                aggnonce = NonceAgg(pubnonces)
                aggnonce_bytes = (aggnonce[0].to_bytes_compressed()
                                  + aggnonce[1].to_bytes_compressed())
                if aggnonce_bytes != expected_aggnonce:
                    failures.append(f"Sign #{index}: {comment} (aggnonce mismatch)")
                    continue

                psigs = [
                    Sign(secnonces[i], sks[i], msgs[i], aggnonce, pks, msgs, pubnonces)
                    for i in range(len(sks))
                ]
                derived_psigs = [bytes_from_int(p) for p in psigs]
                if derived_psigs != expected_psigs:
                    failures.append(f"Sign #{index}: {comment} (partial sig mismatch)")
                    continue

                for i in range(len(sks)):
                    if not PartialSigVerify(psigs[i], aggnonce, pks, msgs, pubnonces, i):
                        failures.append(f"Sign #{index}: {comment} (PartialSigVerify failed for signer {i})")
                        break
                else:
                    R, s = SigAgg(aggnonce, pks, msgs, pubnonces, psigs)
                    actual_sig = R.to_bytes_xonly() + bytes_from_int(s)
                    if actual_sig != expected_sig:
                        failures.append(f"Sign #{index}: {comment} (aggsig mismatch)")
                    elif not Verify(pks, msgs, (R, s)):
                        failures.append(f"Sign #{index}: {comment} (Verify failed)")
            except Exception as e:
                failures.append(f"Sign #{index}: {comment} (raised {e!r})")

    return failures


def run_partial_sig_verify_tests() -> List[str]:
    failures = []

    with open(PARTIAL_SIG_VERIFY_VECTORS, newline="", encoding="utf-8") as f:
        reader = csv.reader(f)
        next(reader)

        for row in reader:
            (index, signer_index_str, psig_str, aggnonce_str,
             pks_str, msgs_str, pubnonces_str,
             expected_result, comment) = row
            expected = (expected_result == "TRUE")

            try:
                signer_index = int(signer_index_str)
                psig = int_from_bytes(bytes.fromhex(psig_str))
                aggnonce = parse_pubnonce(bytes.fromhex(aggnonce_str))
                pks = [GE.from_bytes_xonly(b) for b in parse_hex_list(pks_str)]
                msgs = parse_hex_list(msgs_str)
                pubnonces = [parse_pubnonce(b) for b in parse_hex_list(pubnonces_str)]
                result = PartialSigVerify(psig, aggnonce, pks, msgs, pubnonces, signer_index)
            except Exception:
                result = False

            if result != expected:
                failures.append(f"PartialSigVerify #{index}: {comment}")

    return failures


def run_verify_tests() -> List[str]:
    failures = []

    with open(VERIFY_VECTORS, newline="", encoding="utf-8") as f:
        reader = csv.reader(f)
        next(reader)

        for row in reader:
            index, pks_str, msgs_str, sig_str, expected_result, comment = row
            expected = (expected_result == "TRUE")

            try:
                pks = [GE.from_bytes_xonly(b) for b in parse_hex_list(pks_str)]
                msgs = parse_hex_list(msgs_str)
                if len(pks) != len(msgs):
                    raise ValueError("pubkey/message count mismatch")
                R, s = parse_sig(bytes.fromhex(sig_str))
                result = Verify(pks, msgs, (R, s))
            except Exception:
                result = False

            if result != expected:
                failures.append(f"Verify #{index}: {comment}")

    return failures


def main():
    for filename in [SIGN_VECTORS, VERIFY_VECTORS, PARTIAL_SIG_VERIFY_VECTORS]:
        if not os.path.exists(filename):
            print(f"ERROR: Missing {filename}. Run gen_test_vectors.py first.")
            sys.exit(1)

    failures = []
    failures.extend(run_sign_tests())
    failures.extend(run_partial_sig_verify_tests())
    failures.extend(run_verify_tests())

    if failures:
        print("FAILED:")
        for f in failures:
            print(f"  {f}")
        sys.exit(1)
    else:
        print("All tests have passed.")
        sys.exit(0)


if __name__ == "__main__":
    main()
